sudo: false

language: bash

os:
  - linux

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
env:
 matrix:
  - DAVINCI=0 MODEL=0
  - DAVINCI=1 MODEL=0
  - DAVINCI=2 MODEL=0
  - DAVINCI=3 MODEL=0
  - DAVINCI=1 MODEL=1
  - DAVINCI=2 MODEL=1
  - DAVINCI=4 MODEL=1
  
before_script:
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - mv arduino-1.6.5 $HOME/arduino_ide
  - mkdir -p $HOME/.arduino15/packages/arduino/hardware/sam
  - cd $HOME/.arduino15/packages/arduino/hardware/sam
  - wget http://downloads.arduino.cc/cores/sam-1.6.4.tar.bz2
  - tar xf sam-1.6.4.tar.bz2
  - mkdir -p $HOME/.arduino15/packages/arduino/tools/arm-none-eabi-gcc
  - cd $HOME/.arduino15/packages/arduino/tools/arm-none-eabi-gcc
  - wget http://downloads.arduino.cc/gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
  - tar xf gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
  - mv gcc-arm-none-eabi-4.8.3-2014q1 4.8.3-2014q1
  - cp -f "$TRAVIS_BUILD_DIR/src/ArduinoDUE/AdditionalArduinoFiles/Arduino - 1.6.5 -Due 1.6.4/Arduino15/packages/hardware/sam/1.6.4/variants/arduino_due_x/variant.cpp" $HOME/.arduino15/packages/arduino/hardware/sam/1.6.4/variants/arduino_due_x/variant.cpp 
  

script:
  - cd $TRAVIS_BUILD_DIR
  - source command.sh
  - export PATH="$HOME/arduino_ide:$PATH"
  - arduino --board arduino:sam:arduino_due_x --save-prefs
  - arduino --get-pref sketchbook.path
  - sed -i "s/#define DAVINCI 0 /#define DAVINCI $DAVINCI /g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define DAVINCI 1 /#define DAVINCI $DAVINCI /g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define DAVINCI 2 /#define DAVINCI $DAVINCI /g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define DAVINCI 3 /#define DAVINCI $DAVINCI /g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define DAVINCI 4 /#define DAVINCI $DAVINCI /g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define MODEL  1/#define MODEL  $MODEL/g" ./src/ArduinoDUE/Repetier/Configuration.h
  - sed -i "s/#define MODEL  0/#define MODEL  $MODEL/g" ./src/ArduinoDUE/Repetier/Configuration.h
  - head -n 30 ./src/ArduinoDUE/Repetier/Configuration.h
  - build_sketch ./src/ArduinoDUE/Repetier/Repetier.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
